// <auto-generated/
namespace NombreMagique.Shared;

public partial class Game
{
    private const int Lifes = 5;
    private const int NbMin = 1;
    private const int NbMax = 20;

    private int nbMagic; // nombre magique
    private bool? gameWon; // gagné, perdu, null = en cours
    private int NbRemainingLifes; // vies restantes
    private int? value; // valeur entrée par l'utilisateur
    private string indice; // ni le nombre est plus grand ou plus petit



    protected override void OnInitialized()
    {
        InitGame();
    }

    private void InitGame()
    {
        gameWon = null;
        nbMagic = Random.Shared.Next(NbMin, NbMax + 1);
        NbRemainingLifes = Lifes;
        value = null;
        indice = null;

    }

    private void CheckNumber()

    {
        

        if (value == nbMagic)
        {
            gameWon = true;
            indice = null;
            return;


        }
        NbRemainingLifes--;
        if (NbRemainingLifes <= 0)
        {
            gameWon = false;
            indice = null;
            return;
        }
        if (value > nbMagic) indice = " Le nombre magique est plus petit.";
        else if (value < nbMagic) indice = " Le nombre magique est plus grand.";
    }

}